package generator

import (
	"fmt"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/griffin/go-shellify/internal/registry"
)

// Generator interface for different shell types
type Generator interface {
	Generate(modules []registry.Module, outputPath string, verbose bool) (string, error)
	GetFileExtension() string
	GetShellType() string
}

// filterModulesForPlatform filters modules based on current platform
func filterModulesForPlatform(moduleList []registry.Module) []registry.Module {
	currentOS := runtime.GOOS
	var filtered []registry.Module

	for _, module := range moduleList {
		// If no platforms specified, assume it works on all platforms
		if len(module.Platforms) == 0 {
			filtered = append(filtered, module)
			continue
		}

		// Check if current platform is supported
		supported := false
		for _, platform := range module.Platforms {
			if platform == currentOS || platform == "all" {
				supported = true
				break
			}
		}

		if supported {
			filtered = append(filtered, module)
		}
	}

	return filtered
}

// filterModulesForShell filters modules based on shell compatibility
func filterModulesForShell(moduleList []registry.Module, shellType string) []registry.Module {
	var filtered []registry.Module

	for _, module := range moduleList {
		// If no shells specified, assume it works with all shells
		if len(module.Shells) == 0 {
			filtered = append(filtered, module)
			continue
		}

		// Check if current shell is supported
		supported := false
		for _, shell := range module.Shells {
			if shell == shellType || shell == "all" {
				supported = true
				break
			}
		}

		if supported {
			filtered = append(filtered, module)
		}
	}

	return filtered
}

// generateHeader creates a standard header for generated scripts
func generateHeader(shellType string) string {
	comment := "#" // All supported shells use # for comments

	header := fmt.Sprintf(`%s Generated by go-shellify
%s Do not edit this file directly - it will be overwritten
%s To customize, edit your go-shellify configuration and regenerate

`, comment, comment, comment)

	return header
}

// escapeString escapes special characters for shell scripts
func escapeString(s string, shellType string) string {
	switch shellType {
	case "powershell":
		// PowerShell string escaping
		s = strings.ReplaceAll(s, "'", "''")
		s = strings.ReplaceAll(s, "`", "``")
		return s
	case "fish":
		// Fish shell escaping
		s = strings.ReplaceAll(s, "\\", "\\\\")
		s = strings.ReplaceAll(s, "'", "\\'")
		return s
	default:
		// Bash/Zsh escaping
		s = strings.ReplaceAll(s, "\\", "\\\\")
		s = strings.ReplaceAll(s, "'", "'\"'\"'")
		return s
	}
}

// generateModuleSection creates a section header for a module
func generateModuleSection(moduleName, description, shellType string) string {
	comment := "#" // All supported shells use # for comments

	section := fmt.Sprintf(`
%s ===== %s =====
%s %s
`, comment, moduleName, comment, description)

	return section
}

// resolveOutputPath resolves the output path for generated scripts
func resolveOutputPath(outputPath, shellType string) string {
	var filename string
	switch shellType {
	case "powershell":
		filename = "go-shellify.ps1"
	case "fish":
		filename = "go-shellify.fish"
	default:
		filename = "go-shellify.sh"
	}

	return filepath.Join(outputPath, filename)
}